{{- if .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "biometrics.fullname" . }}-pdb
  labels:
    {{- include "biometrics.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "biometrics.selectorLabels" . | nindent 6 }}
      app: {{ include "biometrics.fullname" . }}-opencode-server
{{- end }}
